# Generated by Django 4.0.3 on 2022-06-05 10:04

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('metakeyword', models.CharField(max_length=200, null=True)),
                ('header_image', models.ImageField(upload_to='header_image')),
                ('upload_fonts', models.FileField(upload_to='upload_fonts')),
                ('short_dis', froala_editor.fields.FroalaField()),
                ('long_dis', froala_editor.fields.FroalaField()),
                ('char_maping', models.ImageField(upload_to='char_maping')),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(max_length=50)),
                ('ouremail', models.EmailField(max_length=254)),
                ('copyright', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='websiteimages')),
                ('websitediscription', froala_editor.fields.FroalaField()),
                ('favicon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', froala_editor.fields.FroalaField()),
                ('privacypolicy', froala_editor.fields.FroalaField()),
                ('termsandcondition', froala_editor.fields.FroalaField()),
                ('ourpages', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
