# Generated by Django 4.0.3 on 2022-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fonts_total_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonts',
            name='charimg_alt',
            field=models.CharField(default='arabic fonts charecter maping image', max_length=100),
        ),
        migrations.AddField(
            model_name='fonts',
            name='headerimg_alt',
            field=models.CharField(default='arabic fonts', max_length=100),
        ),
    ]
