# Generated by Django 4.0.3 on 2022-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fonts_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostdownloaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
